fix clean

diff --git a/build-jenkins b/build-jenkins
--- a/build-jenkins
+++ b/build-jenkins
@@ -16,13 +16,15 @@ then
   echo
   echo "-- PROJECT CLEANING --"
   echo
-  DERIVEDDATA_DIR=$(grep -oE "/usr/bin/touch -c .*\.app" "$DIR/../output/build.log" | head -n1 | sed -e 's/.*\ \(.*\)\/Build\/.*/\1/')
+  DERIVEDDATA_DIR=$(grep -oE "/usr/bin/touch -c .*\.app" "$DIR/../output/build.log" | head -n1 | sed -e 's/.*\ \(.*\)\/Build\/.*/\1/' 2> /dev/null)
   if [ -d "$DERIVEDDATA_DIR" ]
   then
     rm -rf "$DERIVEDDATA_DIR"
     echo "[DEBUG] DerivedData $DERIVEDDATA_DIR is removed"
   else
-    echo "[WARNING] DerivedData $DERIVEDDATA_DIR is missed"   
+    echo "[ERROR] DerivedData dir $DERIVEDDATA_DIR is not found"
+    echo "[INFO] First build project and then you may clean it"
+    exit 1
   fi
   
   echo
